site_name: TemplatePy
site_url: https://sea-ai.github.io/templatepy
watch: [mkdocs.yml, README.md, templatepy]

repo_url: https://github.com/SEA-AI/templatepy
repo_name: SEA-AI/templatepy

theme:
  name: material
  font:
    text: Roboto  # Saira is used in our app
    code: Fira Code
  icon:
    repo: fontawesome/brands/github
  features:
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.instant
    # - navigation.tabs
    #- navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Playbook:
    - GitHub Templates: playbook/github-templates.md
    - pyproject.toml: playbook/pyproject-toml.md
    - uv Package Manager: playbook/uv.md
    - Ruff: playbook/ruff.md
    - MkDocs: playbook/mkdocs.md
    - Testing with pytest: playbook/testing.md
    - GitHub Actions: playbook/github-actions.md
    - VS Code Settings: playbook/vscode.md
  - API reference: reference/

markdown_extensions:
  - abbr
  - attr_list
  - toc:
      permalink: ⚓︎
      permalink_title: Link to Heading
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - !relative  # dir of current Markdown file
        # NB: does not work with the virtual files generated by mkdocs-gen-files,
        # ref https://github.com/oprypin/mkdocs-gen-files/issues/25
        - !relative $docs_dir  # dir of docs
        - !relative $config_dir  # dir of mkdocs.yml
      auto_append:
        - includes/abbreviations.md
  - admonition
  - pymdownx.details  # allow for collapsible admonitions
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - autorefs:
      resolve_closest: true
  - section-index
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enabled: !ENV [DEPLOY, false]
      enable_creation_date: true
      type: timeago
  # - git-committers:
  #     repository: SEA-AI/templatepy
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          # paths: [templatepy]  # not needed, we use gen-files plugin
          inventories:
          - https://docs.python.org/3/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://onnx.ai/onnx/objects.inv
          - https://pytorch.org/docs/stable/objects.inv
          - https://pytorch.org/vision/stable/objects.inv
          - https://docs.voxel51.com/objects.inv  # not really working :(
          options:
            docstring_style: "google"
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: spacy
            filters: []  # show private methods (starting with _)
            inherited_members: false
            merge_init_into_class: true
            # parameter_headings: true
            separate_signature: true
            # show_object_full_path: true
            show_root_heading: true
            show_root_full_path: true
            show_root_members_full_path: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
            extensions:
              - griffe_fieldz: {include_inherited: true}
              - griffe_pydantic
